name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # runs every hour

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export environment variables from secrets
        run: |
          echo "TWITTER_BEARER=${{ secrets.TWITTER_BEARER }}" >> $GITHUB_ENV
          echo "BSKY_HANDLE=${{ secrets.BSKY_HANDLE }}" >> $GITHUB_ENV
          echo "BSKY_APP_PASSWORD=${{ secrets.BSKY_APP_PASSWORD }}" >> $GITHUB_ENV

      - name: Debug check if secrets are set
        run: |
          echo "TWITTER_BEARER length: ${#TWITTER_BEARER}"
          echo "BSKY_HANDLE length: ${#BSKY_HANDLE}"
          echo "BSKY_APP_PASSWORD length: ${#BSKY_APP_PASSWORD}"

      - name: Run mirror script
        run: python main.py
