name: update
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod # or remove if not needed

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug secrets
        run: |
          echo "TWITTER_BEARER is set: ${TWITTER_BEARER:+yes}"
          echo "BSKY_HANDLE: '${BSKY_HANDLE}'"
          echo "BSKY_APP_PASSWORD: '${BSKY_APP_PASSWORD}'"
        env:
          TWITTER_BEARER: "${{ secrets.TWITTER_BEARER }}"
          BSKY_HANDLE: "${{ secrets.BSKY_HANDLE }}"
          BSKY_APP_PASSWORD: "${{ secrets.BSKY_APP_PASSWORD }}"

      - name: Run the Python script
        run: python main.py
        env:
          TWITTER_BEARER: "${{ secrets.TWITTER_BEARER }}"
          BSKY_HANDLE: "${{ secrets.BSKY_HANDLE }}"
          BSKY_APP_PASSWORD: "${{ secrets.BSKY_APP_PASSWORD }}"
