name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # runs every hour

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run mirror script
        env:
          TWITTER_BEARER: ${{ secrets.TWITTER_BEARER }}
          BSKY_HANDLE: ${{ secrets.BKSY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BKSY_APP_PASSWORD }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          # Debug output
          echo "TWITTER_BEARER length: ${#TWITTER_BEARER}"
          echo "BSKY_HANDLE length: ${#BKSY_HANDLE}"
          echo "BSKY_APP_PASSWORD length: ${#BKSY_APP_PASSWORD}"
          
          # Run the script
          python main.py
